boards/urls.py
from django.urls import path

from .views import AboutView
from . import views

app_name = 'boards'
urlpatterns = [
    path('', views.index, name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('topic_request/', views.topic_request, name='request_list'),
    path('request/create', views.topic_request_create, name='request_create'),
    path('request/recommendation/', views.request_recommendation, name='request_recommendation'),
    
    # Topics
    path('topic/<slug:slug>/', views.topic_view, name='topic'),
    path('topic/favorite/add/', views.topic_favorite_view, name='topic_favorite'),
     
    # Posts
    path('post/<uuid:pk>/', views.post_view, name='post'),
    path('post/likes/', views.post_likes_view, name='post_likes'),
    path('write/<slug:slug>/', views.create_post_view, name='create'),
    path('edit/<uuid:pk>', views.edit_post_view, name='edit'),
    path('delete/<uuid:pk>', views.delete_post_view, name='delete'),
    
    # Comments
    path('post/<uuid:pk>/addcomment/', views.add_comment_view, name='comment'),
    path('post/comment/delete/<uuid:pk>/', views.delete_comment_view, name='comment-delete'),
    # path('post/comment/edit/<uuid:pk>/', views.edit_comment_view, name='comment-edit'),
    
]

chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'
urlpatterns = [
    path('<str:topic>/', views.chat_room, name='room' ),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('communityadminpageforme/', admin.site.urls),
    path('', include('boards.urls')),
    path('user/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('chat/', include('chat.urls')),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

boards/forms.py
from django import forms
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget

from mptt.forms import TreeNodeChoiceField
from .models import Post, Comment, TopicRequest


class PostCreationForm(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = ['title', 'post',]
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control mb-4',
                'placeholder': 'Subjekt',
            }),
            'post': SummernoteWidget(),
        }
        

class CommentCreationForm(forms.ModelForm):
    parent = TreeNodeChoiceField(queryset=Comment.objects.all())
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self.fields['parent'].widget.attrs.update({'class': 'd-none'})
        self.fields['parent'].label = ''
        self.fields['parent'].required = False
        
    
    class Meta:
        model = Comment
        fields = ['comment', 'parent']
        labels = {
            'comment': ('Kommentar'),
        }
        widgets = {
            'comment': SummernoteWidget(attrs={
                'summernote': {
                    'width': '100%',
                    'height': '280',
                    'toolbar': [
                        ['style', []],
                        ['font', ['bold', 'underline',]],
                        ['fontname', []],
                        ['color', ['color']],
                        ['insert', ['link',]],
                    ],
                }
            })
        }
        

class PostSearchFormInTopic(forms.Form):
    search_option = (
        ('title_post', 'Thema + Inhalt'),
        ('writer', 'Schwätzer'),
    )
    select = forms.ChoiceField(
        choices=search_option,
        label='',
        widget=forms.Select(attrs={'class': 'form-control form-control-sm'}),
    )
    search = forms.CharField(label='')
    
    
class TopicRequestForm(forms.ModelForm):
    
    class Meta:
        model = TopicRequest
        fields = ['category', 'topic', 'purpose']
        widgets = {
            'purpose': forms.Textarea(attrs={
                'placeholder': 'Sie werden diese Anfrage nicht löschen können'}
            )
        }
        labels = {
            'category': 'Kategorie',
            'topic': 'Thema',
            'purpose': 'Absicht',
        }

boards/views.py
from django.conf import settings
from django.views.decorators.cache import cache_page
from django.core.cache.backends.base import DEFAULT_TIMEOUT
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponse
from django.core.paginator import Paginator
from django.views.decorators.csrf import ensure_csrf_cookie
from django.db.models import Q

from .models import Board, Topic, Post, Comment, IpModel, TopicRequest
from .forms import (
    PostCreationForm,
    CommentCreationForm,
    PostSearchFormInTopic,
    TopicRequestForm,
)

CACHE_TTL = getattr(settings, 'CACHE_TTL', DEFAULT_TIMEOUT)
# @cache_page(CACHE_TTL)

def index(request):
    # Display all boards(higher Categories) with linked Topics.
    # to create cards according to the number of baords.
    
    boards = Board.objects.all()
    context = {
        'boards': boards,
        'range': range(boards.count())
    }
    return render(request, 'home.html', context)


def topic_view(request, slug):
    # This topic view might be better with generic ListView.
    # Display all posts from specific topic.
    # there is also 3rd party packages for pagination.
    
    topic = Topic.objects.get(slug=slug)
    posts = topic.post_set.all()
    
    post_search = PostSearchFormInTopic()
    
    if 'search' in request.GET:
        
        search = request.GET.get('search')
        select = request.GET.get('select')

        if select == 'title_post':
            queried_posts = posts.filter(
                Q(title__icontains=search) | Q(post__icontains=search))
            
        elif select == 'writer':
            queried_posts = posts.filter(Q(writer__username__icontains=search))
        
        else:
            pass
        
        # limit the posts objects to queried post from post search section
        posts = queried_posts    
        
    paginator = Paginator(posts, 20)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    context = {
        'topic': topic,
        'posts': posts,
        'page_obj': page_obj,
        'post_search': post_search,
    }
    return render(request, 'boards/topic_view.html', context)


@ensure_csrf_cookie
def topic_favorite_view(request):
    
    if not request.user.is_authenticated:
        return JsonResponse({'result': 'false'})
    
    if request.is_ajax():
        topic = get_object_or_404(Topic, slug=request.POST.get('topic_slug'))
        
        response = ''
        if topic.favorites.filter(id=request.user.id).exists():
            topic.favorites.remove(request.user)
            topic.save()
            response = {'result': 'removed'}

        else:
            topic.favorites.add(request.user)
            topic.save()
            response = {'result': 'added'}

        return JsonResponse(response, status=200)


def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


def post_view(request, pk):
    
    # display specific post and comment form which will be dealt in add-comment function by ajax.
    post = Post.objects.get(id=pk)
    comments = post.comments.all()
    form = CommentCreationForm()
    
    # Check if request user ip already exists in Post model.
    # get_or_create returns tuple, (object and boolean(created or not))
    ip = get_client_ip(request)
    visitor, created = IpModel.objects.get_or_create(ip=ip)
    
    if not visitor.post.filter(id=post.id).exists():
        print('there\'s no post in this ip')
        visitor.post.add(post)
        visitor.save()
        post.view_count += 1
        post.save()
            
    context = {
        'post': post,
        'form': form, 
        'comments': comments,
        'topic': post.topic,
    }
    return render(request, 'boards/post_view.html', context)


@login_required(login_url='account_login')
def create_post_view(request, slug):
    
    topic = Topic.objects.get(slug=slug)
    form = PostCreationForm()
    
    if request.method == 'POST':
        form = PostCreationForm(request.POST)
        
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.topic = Topic.objects.get(slug=slug)
            new_post.writer = request.user # getting current user from request.
            new_post.save()
            return redirect('boards:topic', slug)
    
    context = {'form': form, 'topic': topic}
    return render(request, 'boards/create_post_view.html', context)


@login_required(login_url='account_login')
def edit_post_view(request, pk):
    
    post = Post.objects.get(id=pk)
    previous_page = request.META.get('HTTP_REFERER', '/')
    
    if request.user != post.writer:
        return redirect('boards:post', pk)
    
    else:
        form = PostCreationForm(instance=post)
        
        if request.method == 'POST':
            form = PostCreationForm(request.POST, instance=post)
            
            if form.is_valid():
                form.save()
                return redirect('boards:post', pk)
        
        context = {
            'form': form,
            'post': post, 
            'topic': post.topic,
            'previous_page': previous_page,
        }
        return render(request, 'boards/edit_post_view.html', context)


@login_required(login_url='account_login')
def delete_post_view(request, pk):
    
    post = Post.objects.get(id=pk)
    slug = post.topic.slug
    previous_page = request.META.get('HTTP_REFERER')
    
    if request.user != post.writer:
        return redirect('boards:post', pk)
    
    else:
        if request.method == 'POST':
            post.delete()
            return redirect('boards:topic', slug)
        
        context = {'post': post, 'topic': post.topic, 'previous_page': previous_page}
        return render(request, 'boards/delete_post_view.html', context)


def post_likes_view(request):
    
    if not request.user.is_authenticated:
        return JsonResponse({'result': 'false'})
    
    if request.is_ajax():
        post = get_object_or_404(Post, id=request.POST.get('post_id'))
        
        response = ''
        if post.likes.filter(id=request.user.id).exists():
            post.likes.remove(request.user)
            post.like_count -= 1
            post.save()
            response = {'result': 'minus', 'count': post.like_count}

        else:
            post.likes.add(request.user)
            post.like_count += 1
            post.save()
            response = {'result': 'plus', 'count': post.like_count}

        return JsonResponse(response, status=200)
    

def add_comment_view(request, pk):
    # getting a request from front ajax and response.
    
    data = {}
    if request.is_ajax():
        if not request.user or not request.user.is_authenticated:
            data['success'] = 'false'
            data['url'] = 'http://127.0.0.1:8000/accounts/login/'
            return JsonResponse(data, status=404)
        
        form = CommentCreationForm(request.POST)
        
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.writer = request.user
            new_comment.post = Post.objects.get(id=pk)
            new_comment.save()
            
            # Since data from views can not be rendered dynamically in html,
            # django should send rendered data in response to ajax call.
            data['username'] = new_comment.writer.username
            data['comment'] = new_comment.comment
            data['id'] = new_comment.id
    
            return JsonResponse(data, status=200)
    
    return redirect('boards:post', pk)


def delete_comment_view(request, pk):
    
    comment = Comment.objects.get(id=pk)
    post = comment.post
    
    if request.user.is_authenticated and request.user == comment.writer:
        comment.delete()
        return redirect('boards:post', post.id)

    return redirect('boards:post', post.id)


def topic_request(request):
    
    requests = TopicRequest.objects.all()
    
    paginator = Paginator(requests, 20)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    context = {'request_obj': page_obj}
    return render(request, 'boards/topic_request_list.html', context)


@login_required(login_url='account_login')
def topic_request_create(request):
    
    form = TopicRequestForm()
    
    if request.method == 'POST':
        form = TopicRequestForm(request.POST)
        
        if form.is_valid():
            new_request = form.save(commit=False)
            new_request.writer = request.user
            new_request.save()
            return redirect('boards:request_list')

    
    context = {'form': form}
    return render(request, 'boards/topic_request_create.html', context)


def request_recommendation(request):
    
    if not request.user.is_authenticated:
        return JsonResponse({'result': 'false'})
    
    if request.is_ajax():
        request_id = request.POST.get('request_id')
        requested_topic = get_object_or_404(TopicRequest, id=request_id) 
               
        response = {
                'request_id': requested_topic.id,
                }
        if requested_topic.recommendations.filter(id=request.user.id).exists():
            requested_topic.recommendations.remove(request.user)
            requested_topic.like_count -= 1
            requested_topic.save()
            response['result'] = 'minus'
            
        
        else:
            requested_topic.recommendations.add(request.user)
            requested_topic.like_count += 1
            requested_topic.save()
            response['result'] = 'plus'
    
        return JsonResponse(response, status=200)



class AboutView(TemplateView):

templates/boards/post_view.html
{% extends 'base.html' %}
{% load static }
{% load humanize %}
{% load crispy_forms_tags %}
{% load post_extras %}

{% block title %}
    Board: {{ topic }}
{% endblock title %}


{% block content %}
{% include 'covers/cover-posts.html' %}

<div class="container-fluid mt-2">
    <div class="row">

        <div class="col-md-1"></div>

        <div class="col-md p-0">
            <div class="post-header-container">
                <p class="h2 text-center text-monospace">
                    <a href="{% url 'boards:topic' topic.slug %}">{{ topic }}</a>
                </p>
                <hr>
                <p class="h4 text-left text-monospace post-title">{{ post.title }}</p>
                <div class="post-info">
                    <p class="post-info-views-ups"><span>{{ post.view_count }} Ansichten</span> <span id="post-info-ups">{{ post.like_count }} Up</span></p>  
                    <p>{{ post.writer.username }} | {{ post.date_created }}</p>
                    <hr>                       
                </div>
            </div>

            <div class="post-content-section">
                <div class="row">
                    <div class="col">
                        <div class="container-fluid p-0">
                            <div class="post-content-part">
                                {{ post.post|safe }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="reader-likes-section">
                <div class="fire-icon">
                    <i class="fab fa-hotjar" style="color: {% likeOrNot user post.id %}" id="likeIcon" data-postid="{{ post.id }}" data-url="{% url 'boards:post_likes' %}"></i>
                    <p id="like-counts">{{ post.like_count }} Up</p>
                </div>
            </div>

            <div class="writer-edit-delete-section mt-5">
                {% if request.user == post.writer %}
                <a href="{% url 'boards:edit' post.id %}"><button class="btn btn-sm btn-secondary">Post Überarbeiten</button></a>
                <a href="{% url 'boards:delete' post.id %}"><button class="btn btn-sm btn-danger">Post Löschen</button></a>
                {% endif %}
            </div>

            <!-- Commentttt section was here -->
            <div class="comments-list-section" id="comments-list">
                <div class="mb-3 mt-3">
                    <button class="float-right btn btn-dark btn-sm text-monospace" id="commentOpenCloseButton">Schließen</button>
                    {% with comments.count as total_counts %}
                    {% if total_counts == 0 %}
                        <h3>{{ total_counts }} Kommentar</h3>
                    {% else %}
                        <h3>{{ total_counts }} Kommentar{{ total_counts|pluralize:",e"}}</h3>
                    {% endif %}
                    {% endwith %}
                    <hr class="comments-hr mt-2">
                </div>
                
                

                {% load mptt_tags %}
                <div class="mptt-comments" id="mpttComments">
                    {% recursetree comments %}
                        {% if node.writer == user and user.is_authenticated %}
                            <div class="comment-dropdown dropleft">
                                <i class="fas fa-ellipsis-v" id="edit-delete-dots" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
                                <div class="dropdown-menu" aria-labelledby="edit-delete-dots">
                                <a class="dropdown-item" data-toggle="modal" data-target="#deleteCommentModal{{ node.id }}">Löschen</a>
                            </div>
                            </div>

                            <div class="delete-comment-modal-section">
                                <div class="modal fade" id="deleteCommentModal{{ node.id }}" tabindex="-1" aria-labelledby="deleteComment" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title text-monospace" id="deleteComment">Kommentar Löschen</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body text-monospace">
                                                Wollen Sie Ihren Kommentar löschen?
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-sm btn-secondary text-monospace" data-dismiss="modal">Abbrechen</button>
                                                <a href="{% url 'boards:comment-delete' node.id %}"><button type="button" class="btn btn-sm btn-primary text-monospace">Löschen</button></a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                        <div class="comment-info-container" id="comment-{{ node.id }}">
                            <p class="comment-info comment-writer-time">{{ node.writer.username }} | {{ node.date_created|naturaltime }}</p>
                            <p class="comment-content comment-new-content">{{ node.comment|safe }}</p>
                            {% if node.level < 3 %}
                            <button class="commentReplyButton btn btn-sm btn-outline-info mb-2" data-id="{{ node.id }}" data-postid="{{ post.id }}">Antworten</button>
                            {% endif %}
                            <hr>
                        </div>

                        {% if not node.is_leaf_node %}
                        <div class="children pl-3">
                            {{ children }}
                        </div>  
                        {% endif %}

                    {% endrecursetree %}
                </div>
            </div>
            
            <div class="comments-form-section mt-3">
                <form data-url="{% url 'boards:comment' post.id %}" id="commentForm">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button class="btn btn-outline-dark text-monospace" type="submit" id="commentButton">Kommentieren</button>
                </form>
            </div>

        </div>

        <div class="col-md-1"></div>

    </div>
</div>

{% endblock content %}


<!-- <div class="comments-list-section" id="comments-list">
    {% with comments.count as total_counts %}
        {% if total_counts == 0 %}
            <h3>{{ total_counts }} Kommentar</h3>
        {% else %}
            <h3>{{ total_counts }} Kommentar{{ total_counts|pluralize:",e"}}</h3>
        {% endif %}
    {% endwith %}

    <h3>Kommentare</h3>
    <hr class="comments-hr">
    {% for comment in comments %}
        
        {% if comment.writer == request.user and request.user.is_authenticated %}
        <div class="comment-dropdown dropleft">
            <i class="fas fa-ellipsis-v" id="edit-delete-dots" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
            <div class="dropdown-menu" aria-labelledby="edit-delete-dots">
            <a class="dropdown-item" data-toggle="modal" data-target="#deleteCommentModal{{ comment.id }}">Löschen</a>
            <a class="dropdown-item comment-edit-button" data-url="{% url 'boards:comment-edit' comment.id %}">Überarbeiten</a>
          </div>
        </div>

        <div class="delete-comment-modal-section">
            <div class="modal fade" id="deleteCommentModal{{ comment.id }}" tabindex="-1" aria-labelledby="deleteComment" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title text-monospace" id="deleteComment">Kommentar Löschen</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body text-monospace">
                            Wollen Sie Ihren Kommentar löschen?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-sm btn-secondary text-monospace" data-dismiss="modal">Abbrechen</button>
                            <a href="{% url 'boards:comment-delete' comment.id %}"><button type="button" class="btn btn-sm btn-primary text-monospace">Löschen</button></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        <div class="comment-info-container" id="comment-{{ comment.id }}">
            <p class="comment-info comment-writer-time">{{ comment.writer.username }} | {{ comment.date_created|naturaltime }}</p>
            <p class="comment-content comment-new-content">{{ comment.comment|safe }}</p>
        </div>
    <hr>
    {% endfor %}
</div> -->

templates/boards/topic_view.html
{% extends 'base.html' %}
{% load static }
{% load crispy_forms_tags %}
{% load post_extras %}
{% block title %}
    Board: {{ topic }}
{% endblock title %}


{% block content %}
{% include 'covers/cover-topics.html' %}

<div class="container-fluid mt-2">
    <div class="row">

        <div class="col-md-1"></div>

        <div class="col-md p-0">
            
            <div class="topic-container">
                <a href="{% url 'boards:topic' topic.slug %}" class="h2 text-monospace">{{ topic }}</a>
                <hr>
            </div>

            <div class="button-container">
                <div class="write-button">
                    <span id="favorite-topic" data-toggle="tooltip" data-placement="top" title="Speichern Sie dies als Lieblingsthema" data-topicslug="{{ topic.slug }}" data-url="{% url 'boards:topic_favorite' %}">{% favoriteOrNot user topic.slug %}</span>
                    <a href="{% url 'boards:create' topic.slug %}"><button type="button" class="btn btn-sm btn-outline-dark"><i class="fas fa-keyboard"></i> Schreiben</button></a>
                </div>
                <div>
                    <a href="{% url 'boards:home' %}"><button type="button" class="btn btn-sm btn-outline-dark">Zurück nach Themen</button></a>    
                </div>
            </div>

            <div class="container-fluid p-0">
                <table>
                    <colgroup>
                        <col class="seven">
                        <col class="fifty">
                        <col class="ten">
                        <col class="twenty">
                        <col class="ten">
                    </colgroup>
                    <thead>
                        <tr>
                            <th class="topic-th"><i class="fab fa-hotjar"></i></th>
                            <th class="topic-th">Titel</th>
                            <th class="topic-th">Schwätzer</th>
                            <th class="topic-th">Datum</th>
                            <th class="topic-th">Ansichten</th>
                        </tr>
                    </thead>
                    <tbody>
                        <!-- post pagination -->
                        {% for post in page_obj.object_list %}
                        <tr class="topic-table-row">
                            <td class="post-likes topic-td">{{ post.like_count }}</td>
                            <td class="post-title topic-td"><a href="{% url 'boards:post' post.id %}">{{ post.title }}{% if post.comments.count > 0 %}[{{ post.comments.count }}]{% endif %}</a></td>
                            <td class="post-writer topic-td">{{ post.writer.username }}</td>
                            <td class="post-date topic-td">{{ post.date_created|date:"H:i d, M, y"}}</td>
                            <td class="post-views topic-td">{{ post.view_count }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>

                <!-- pagination pages -->
                <div class="post-pagination-section">
                    <div class="">
                        <div class="page-buttons mt-2 d-flex justify-content-center">
                            {% if page_obj %}
                                <a href="?page=1"><i class="fas fa-fast-backward"></i></a>
                                {% if page_obj.has_previous %}
                                    <a href="?page={{ page_obj.previous_page_number }}"><i class="fas fa-caret-left"></i></a>
                                {% else %}
                                    <a href="?page=1"><i class="fas fa-caret-left"></i></a>
                                {% endif %}
                                
                                {% for num in page_obj.paginator.page_range %}
                                    {% if page_obj.number == num %}
                                        <a href="?page={{ num }}"><strong>{{ num }}</strong></a>
                                    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'+3' %}
                                        <a href="?page={{ num }}">{{ num }}</a>
                                    {% endif %}
                                {% endfor %}
                                                            
                                {% if page_obj.has_next %}
                                    <a href="?page={{ page_obj.next_page_number }}"><i class="fas fa-caret-right"></i></a>
                                {% else %}
                                    <a href="?page={{ page_obj.paginator.num_pages }}"><i class="fas fa-caret-right"></i></a>
                                {% endif %}
                                <a href="?page={{ page_obj.paginator.num_pages }}"><i class="fas fa-fast-forward"></i></a>
                            {% endif %}
                        </div>
                        <div class="post-search d-flex justify-content-center mt-2">
                            <form action="" method="GET">
                                <div class="form-row">
                                    <div class="col">
                                        {{ post_search.select }}
                                    </div>
                                    <div class="col">
                                        {{ post_search.search }}
                                    </div>
                                    <button class="btn btn-sm btn-outline-info float-right" type="submit">Suchen</button>
                                </div>
                            </form>
                        </div>
                        <div class="topic-group-chat-section d-flex justify-content-center mt-3">
                            <a href="{% url 'chat:room' topic.topic %}" class="btn btn-sm btn-block btn-primary" style="width: 32%;">Gruppe Reden</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-1"></div>

    </div>
</div>

{% endblock content %}

<!-- {% for post in posts %}
                        <tr class="topic-table-row">
                            <td class="post-likes topic-td">#</td>
                            <td class="post-title topic-td"><a href="{% url 'boards:post' post.id %}">{{ post.title }}</a></td>
                            <td class="post-writer topic-td">{{ post.writer.username }}</td>
                            <td class="post-date topic-td">{{ post.date_created|date:"H:i d, M, y"}}</td>
                            <td class="post-views topic-td">#</td>
                        </tr>
                        {% endfor %} -->