accounts/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('logout/', views.logout_view, name='logout'),
    path('profile/<str:username>/', views.user_profile_view, name='profile'),
    path('profile/<uuid:pk>/avatar/', views.user_edit, name='avatar'),
    path('account/deletion/<uuid:pk>/', views.user_account_delete, name='delete'),
]

boards/urls.py
from django.urls import path

from .views import AboutView
from . import views

app_name = 'boards'
urlpatterns = [
    path('', views.index, name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('topic_request/', views.topic_request, name='request_list'),
    path('request/create', views.topic_request_create, name='request_create'),
    path('request/recommendation/', views.request_recommendation, name='request_recommendation'),
    
    # Topics
    path('topic/<slug:slug>/', views.topic_view, name='topic'),
    path('topic/favorite/add/', views.topic_favorite_view, name='topic_favorite'),
     
    # Posts
    path('post/<uuid:pk>/', views.post_view, name='post'),
    path('post/likes/', views.post_likes_view, name='post_likes'),
    path('write/<slug:slug>/', views.create_post_view, name='create'),
    path('edit/<uuid:pk>', views.edit_post_view, name='edit'),
    path('delete/<uuid:pk>', views.delete_post_view, name='delete'),
    
    # Comments
    path('post/<uuid:pk>/addcomment/', views.add_comment_view, name='comment'),
    path('post/comment/delete/<uuid:pk>/', views.delete_comment_view, name='comment-delete'),
    # path('post/comment/edit/<uuid:pk>/', views.edit_comment_view, name='comment-edit'),
    
]

chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'
urlpatterns = [
    path('<str:topic>/', views.chat_room, name='room' ),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('communityadminpageforme/', admin.site.urls),
    path('', include('boards.urls')),
    path('user/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('chat/', include('chat.urls')),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

boards/models.py
import uuid
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.conf import settings
from django.contrib.auth import get_user_model
from mptt.models import MPTTModel, TreeForeignKey


class Board(models.Model):
    board = models.CharField(max_length=100)
    slug = models.SlugField(null=False, blank=True)
    date_created = models.DateTimeField(
        verbose_name='date created',
        default=timezone.now
    )
    
    # This makes difference between board and slug, it's used to distinguish in home page collapse cards.
    def __str__(self):
        return self.board.capitalize()
    

class Topic(models.Model):
    board = models.ForeignKey(Board, on_delete=models.PROTECT)
    topic = models.CharField(max_length=100)
    slug = models.SlugField(null=False, blank=True)
    favorites = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='favorite',
        default=None,
        blank=True
    )
    date_created = models.DateTimeField(
        verbose_name='date created',
        default=timezone.now
    )
    
    def __str__(self):
        return self.topic.capitalize()
    
    def get_absolute_url(self):
        return reverse('topic', kwargs={'slug': self.slug})
 
    
# Post Model, View Counter, Thumbs Up need to be updated. 
class Post(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    topic = models.ForeignKey(Topic, on_delete=models.PROTECT)
    writer = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        on_delete=models.SET_NULL
    )
    title = models.CharField(max_length=100)
    post = models.TextField()
    likes = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='like',
        blank=True,
        default=None
    )
    like_count = models.BigIntegerField(default=0)
    view_count = models.BigIntegerField(default=0)
    date_created = models.DateTimeField(
        verbose_name='date created',
        default=timezone.now
    )
    date_updated = models.DateTimeField(
        verbose_name='date updated',
        auto_now=True
    )
    
    class Meta:
        ordering = ['-date_created']
    
    def __str__(self):
        return self.title


class Comment(MPTTModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    writer = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        on_delete=models.SET_NULL
    )
    comment = models.TextField(max_length=1000)
    parent = TreeForeignKey(
        'self',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='children'
    )
    date_created = models.DateTimeField(
        verbose_name='date created',
        default=timezone.now
    )
    date_updated = models.DateTimeField(
        verbose_name='date updated',
        auto_now=True
    )
    
    class MPTTMeta:
        order_insertion_by = ['date_created']
    
    def __str__(self):
        return self.comment       
    
    
class IpModel(models.Model):
    ip = models.CharField(max_length=100)
    post = models.ManyToManyField(Post,
        related_name='viewed_ip',
        blank=True,
        default=None,
    )
    
    def __str__(self):
        return self.ip
    

class TopicRequest(models.Model):
    category = models.CharField(max_length=50)
    topic = models.CharField(max_length=100)
    purpose = models.TextField(max_length=1000)
    writer = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        on_delete=models.SET_NULL
    )
    recommendations = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='recommendation',
        blank=True,
        default=None
    )
    like_count = models.BigIntegerField(default=0)
    date_created = models.DateTimeField(
        verbose_name='date created',
        default=timezone.now
    )
    date_updated = models.DateTimeField(
        verbose_name='date updated',
        auto_now=True
    )
    
    class Meta:
        ordering = ['-date_created']
    
    def __str__(self):
        return f'{self.category} - {self.topic}'

templates/about.html
{% extends 'base.html' %}

{% block title %}
    About Klatsch 
{% endblock title %}

{% block content %}

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md mt-4">
                <div class="jumbotron jumbotron-fluid">
                    <div class="container">
                        <h1 class="display-4">DEUTSCH KLATSCH</h1>
                        <p class="lead">Reden Sie egal was sie möchten</p>
                    </div>
                </div>
            </div>
            <div class="col-md-2"></div>
        </div>
    </div>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap4.6 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <!-- google font -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com"> 
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;500&display=swap" rel="stylesheet">
    <!-- css link -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" integrity="sha384-vSIIfh2YWi9wW0r9iZe7RJPrKwp6bG+s9QZMoITbCckVJqGCCRhc+ccxNcdpHuYu" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <title>{% block title %}Deutsch Klatsch{% endblock %}</title>
</head>
<body>
    <header>
        {% include 'navbar.html' %}
    </header>

    <main>
        {% block content %}
        {% endblock content %}
    </main>
    
    <footer>
        {% include 'footer.html' %}
    </footer>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'js/script.js'%}"></script>
    {% block websocket-content %}
    {% endblock websocket-content %}
</body>
</html>

templates/footer.html
<style>
.footer {
    margin-top: 15%;
    background-color: #373a3b;
    height: 250px;
    width: auto;
}

.copiright {
    color: rgb(184, 182, 182);
    text-align: center;
    font-size: 1.3rem;
    font-family: monospace;
    margin-top: 20px;
}
.contact p {
    color: rgb(184, 182, 182);
    text-align: center;
    font-family: monospace;
    font-size: 1.3rem;
    margin: 0;
}
.contact {
    padding: 8% 0 0;
}

</style>
<div class="container-fluid footer">
    <div class="contact">
        <p>Kontakt</p>
        <p>deutschklatsch@gmail.com</p>
    </div>
    <p class="copiright">© 2021 Deutsch Klatsch</p>
</div>
</div>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Deutsch Klatsch
{% endblock title %}

{% block content %}
{% include 'covers/cover-home.html' %}

<div class="container-fluid mt-2">
    <div class="row">
        <div class="col-md-2">

        </div>
        <div class="col-md-8">

            <p class="h2 text-center text-monospace">Klatsch Kategorie</p>
            <hr>

            <div class="d-flex justify-content-end">
                <p class="text-monospace badge badge-dark" id="topicsToggle">Show All</p>
            </div>

            <div class="accordion" id="boardCategory">
                {% if user.is_authenticated and user.favorite.all.count > 0 %}
                <div class="card bg-dark">
                    <div class="card-header" id="userFavorites">
                    <h2 class="mb-0">
                        <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#favorites" aria-expanded="true" aria-controls="userFavorites">
                            <p class="h3 text-white text-monospace">Lieblingsthema</p>
                        </button>
                    </h2>
                    </div>
                
                    <div id="favorites" class="collapse" aria-labelledby="userFavorites" data-parent="#boardCategory">
                        <div class="card-body">
                            {% for topic in user.favorite.all %}
                                <a href="{% url 'boards:topic' topic.slug %}" class="text-white text-monospace text-decoration-none">{{ topic }}&nbsp;|&nbsp;</a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                {% endif %}
                {% for board in boards %}
                    <div class="card bg-dark">
                        <div class="card-header" id="{{ board.slug }}">
                        <h2 class="mb-0">
                            <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#{{ board }}" aria-expanded="true" aria-controls="{{ board }}">
                                <p class="h3 text-white text-monospace">{{ board }}</p>
                            </button>
                        </h2>
                        </div>
                    
                        <div id="{{ board }}" class="collapse" aria-labelledby="{{ board.slug }}" data-parent="#boardCategory">
                            <div class="card-body">
                                {% for topic in board.topic_set.all %}
                                    <a href="{% url 'boards:topic' topic.slug %}" class="text-white text-monospace text-decoration-none">{{ topic }}&nbsp;|&nbsp;</a>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                {% endfor %}

                <div class="topic-request-section mt-3">
                    <div class="topic-request-button d-flex justify-content-end">
                        <a href="{% url 'boards:request_list' %}"><button class="btn btn-sm btn-outline-dark">Thema Anfrage</button></a>
                    </div>
                </div>

            </div>
        <div class="col-md-2"></div>
    </div>
</div>

{% endblock content %}

templates/navbar.html
<!-- nav bar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand text-monospace" href="{% url 'boards:home' %}">DEUTSCH KLATSCH</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" >
    <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarToggle">
    <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="UserProfileDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
                    {{ user.username }}
                </a>
                <ul class="dropdown-menu" aria-labelledby="UserProfileDropdown">
                    <li><a class="dropdown-item" href="{% url 'user:profile' user.username %}">Profil</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="{% url 'user:logout' %}">Ausloggen</a></li>
                  </ul>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'account_login' %}">Einloggen</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'account_signup' %}">Anmelden</a>
            </li>
        {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'boards:about' %}">Über Klatsch</a>
            </li>
    </ul>
    </div>
</nav>

<!-- login signup modal -->
<!-- Login page -->
<!-- <div class="modal fade" id="loginPage">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header text-center">
                <h4 class="modal-title text-center w-100 font-weight-bold">Login</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="close">&times;</button>
            </div>
            <div class="modal-body mx-3">

                <div class="md-form mb-5">
                    <i class="fas fa-user prefix grey-text"></i>
                    <input type="text" class="form-control validate">
                    <label data-error="wrong" data-success="right">email address</label>
                </div>

                <div class="md-form mb-5">
                    <i class="fas fa-envelope prefix grey-text"></i>
                    <input type="password" class="form-control validate">
                    <label data-error="wrong" data-success="right">password</label>
                </div>

            </div>
            <div class="modal-footer d-flex justify-content-center">
                <button class="btn btn-primary">Login</button>
            </div>
        </div>
    </div>
</div> -->